from blogfront import BlogFront
from bloghandler import BlogHandler
from deletecomment import DeleteComment
from deletepost import DeletePost
from editcomment import EditComment
from likepost import LikePost
from newcomment import NewComment
from newpost import NewPost
from postpage import PostPage
from register import Register
from login import Login
from logout import Logout
from userpage import UserPage
from editpost import EditPost
